#!/bin/bash -e

apt-get -q -y install avnav-update-plugin || true

# Fix a bug documented somewhere in gentoo bug tracker
update-mime-database /usr/share/mime

# Keeping it enabled breaks wifi in nm-applet
systemctl disable dhcpcd.service

touch /tmp/FIRSTRUN
systemctl disable firstRun.service
