#!/bin/bash -e

# this plugin needs systemd running during install
apt-get -q -y install avnav-update-plugin || true
systemctl restart avnav

# Fix a bug documented somewhere in gentoo bug tracker
update-mime-database /usr/share/mime

# Keeping it enabled breaks wifi in nm-applet
systemctl disable dhcpcd.service

if [ -x /boot/first-boot.sh ]
then
  /boot/first-boot.sh || true
fi

touch /tmp/FIRSTRUN
systemctl disable firstRun.service
