#! /bin/bash
application=$1

DESKTOP_SESSION=gnome
export DESKTOP_SESSION

if pidof $(command -v "${application}") > /dev/null ; then
    echo "${application} is already running"
    wmctrl -x -R "$application"
else
    $@
fi
