Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 4
    vb.linked_clone = true if Vagrant::VERSION =~ /^1.8/
  end

 # config.vm.provision "file", source: "../../install-scripts", destination: "/install-scripts"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt-get install -yq proot squashfs-tools qemu kpartx qemu-user p7zip-full git live-build xorriso
  SHELL

end